### PR TITLE
switch to the shortcuts API and use the M key to toggle measure

### LINKED ISSUE #15: [Bug] addon-measure breaks alt functionality on Windows
### Describe the bug

The plugin breaks the original alt-key functionality - ie. displaying the browser menu on Windows. Another related issue is that the plugin gets activated when alt-tabbing to a different window and stays activated when returning back, which makes it incredibly annoying.

### Expected behavior

Use a different key. At least on Windows.

### Environment

 - OS: Windows 10
 - Browser (if applicable): Chrome
 - Browser version (if applicable): 91
 - Storybook: 6.3.0 with addon-essentials

### Workaround
Replace this in `.storybook/main.js`:
```js
addons: [
  '@storybook/addon-essentials',
]
```

With this:
```js
addons: [
  {
    name: '@storybook/addon-essentials',
    options: { measure: false },
  },
]
```

### LINKED ISSUE #19: [Bug] Spurious globals URL parameter
### Describe the bug

Enabling the measure addon causes a spurious `&globals=measureEnabled:false` query parameter when you navigate between stories. This should be the default value & should be provided to the story store so that it only shows in the URL when the value becomes true.

This could also be a bug in Storybook core.

### PR DESCRIPTION
**Pull request by winkerVSbecks**
### What I did
* Switched to the `setAddonShortcut` API
* You can now uses <kbd>m</kbd> shortcut to toggle measure
* @domyen the keyboard shortcut behaves like the toolbar i.e., toggles. You don't have to hold the key down.

@shilman this also resolves the global params issue

fixes #15, fixes #19

<details>
  <summary>📦 Published PR as canary version: <code>2.0.0--canary.21.0b1b9b3.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/addon-measure@2.0.0--canary.21.0b1b9b3.0
  # or 
  yarn add @storybook/addon-measure@2.0.0--canary.21.0b1b9b3.0
  ```
</details>

### CODE REVIEW

**Review by domyen — APPROVED** [review]

File: src/Tool.js [hunk 1]
```diff
@@ -1,23 +1,30 @@
...
       }),
-    [measureEnabled]
+    [updateGlobals, measureEnabled]
   );
 
   useEffect(() => {
-    return useHotKey(updateGlobals);
-  }, []);
+    api.setAddonShortcut(ADDON_ID, {
+      label: "Toggle Measure",
```
Comment (domyen) [inline src/Tool.js]:
```suggestion
      label: "Toggle Measure [M]",
```

**Review by shilman — APPROVED** [review]
LGTM!
